-- game/manager/spawner.script
local constants = require "shared.constants"

local WIDTH = 1280 
local HEIGHT = 720
local MARGIN = 100 

function init(self)
	math.randomseed(os.time())

	-- 1. Lógica original: Generar la bola inicial
	local rx = math.random(MARGIN, WIDTH - MARGIN)
	local ry = math.random(MARGIN, HEIGHT - MARGIN)
	local pos = vmath.vector3(rx, ry, 0)

	factory.create("#ball_factory", pos)
	print("Bola generada en: " .. pos.x .. ", " .. pos.y)

	-- 2. Nueva lógica: Renderizar enemigos iniciales (Chasers)
	-- Vamos a crear 3 enemigos en posiciones aleatorias
	for i = 1, 3 do
		local ex = math.random(MARGIN, WIDTH - MARGIN)
		local ey = math.random(MARGIN, HEIGHT - MARGIN)
		pos = vmath.vector3(ex, ey, 0)

		-- Asumiendo que añadiste un factory para el chaser en este GO
		factory.create("#chaser_factory", pos) 
	end

	-- 3. Nueva lógica: Gestión de Reserva Biológica
	self.hamster_reserve = 2 -- Según tu GDD
end

function on_message(self, message_id, message, sender)
	-- Recibe la señal del jugador cuando cae herido
	if message_id == hash("hamster_down") then
		self.hamster_reserve = self.hamster_reserve - 1

		print('hamster down. Hamsters remaining: '.. self.hamster_reserve)

		if self.hamster_reserve > 0 then
			print("Unidades restantes en reserva: " .. self.hamster_reserve)

			print("Reemplazo desplegado. Misión de rescate iniciada.")
			-- Retardo de 2 segundos para dar peso dramático a la caída
			timer.delay(2, false, function()
				-- El reemplazo aparece en una posición fija (Nido de Viruta/Base)
				-- Asumimos que tienes un factory de player en este mismo GO
				local spawn_pos = vmath.vector3(640, 360, 0) -- Ajustar a tu Base central
				factory.create("#player_factory", spawn_pos)
				
			end)
		else
			print("CRÍTICO: No quedan unidades biológicas. El sistema se apaga.")
			-- Aquí podrías disparar un mensaje de fin de ciclo o reiniciar la colección
			if self.hamster_reserve <= 0 then
				msg.post("main:/game_manager#main", "game_over")
			end
		end
	elseif message_id == hash("hamster_recovered") then
		-- ¡AQUÍ ESTÁ LA MAGIA!
		self.hamster_reserve = self.hamster_reserve + 1
		print("LOG: Unidad reincorporada. Reserva actual: " .. self.hamster_reserve)
	end
end