-- Guardamos las referencias de las habitaciones activas
local rooms = {} 
local last_exit_x = 0 -- Empezamos en el origen del mundo

function init(self)
	-- Cargamos la primera habitación (Sector de memoria inicial)
	local pos = vmath.vector3(0, 0, 0)
	local ids = collectionfactory.create("#room_01", pos)

	-- Guardamos el ID de la salida de esta habitación para la siguiente
	-- Usamos la convención de nombres que definimos: "anchor_exit"
	last_exit_x = 1280 -- Aquí pondrías el ancho que definiste en tu anchor_exit
end

function on_message(self, message_id, message, sender)
	-- Cuando el hámster toca el trigger (room_logic)
	if message_id == hash("player_at_midpoint") then
		print("Unidad 07: Detectado avance. Optimizando memoria...")

		-- Calculamos la posición de la nueva habitación
		local new_pos = vmath.vector3(last_exit_x, 0, 0)

		-- Spawneamos la Room 02 (puedes hacer que sea aleatorio luego)
		collectionfactory.create("#room_02", new_pos)

		-- Actualizamos el punto de salida para la siguiente (acumulativo)
		last_exit_x = last_exit_x + 1280 
	end
end