function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	-- msg.post(".", "acquire_input_focus")
	-- print('Hamster Madness Initialized')
	self.sync_progress = 0
	self.total_enemies_needed = 10 -- O la cantidad que definas para el nivel
	print("SISTEMA DE MEMORIA: Iniciado. Sincronización al 0%")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("enemy_defeated") then
		-- Aumentamos el progreso
		self.sync_progress = self.sync_progress + 1

		-- Calculamos porcentaje
		local percentage = (self.sync_progress / self.total_enemies_needed) * 100
		print("Sincronización de Memoria: " .. percentage .. "%")

		if percentage >= 100 then
			print("MEMORIA RESTAURADA: Nivel Completado.")
			-- Aquí dispararíamos la transición al siguiente nivel o victoria
		end
	end

	if message_id == hash("game_over") then
		-- Detenemos el motor de física y updates (time_step a 0)
		msg.post("@system:", "set_update_frequency", { frequency = 0 })
		print("SISTEMA APAGADO. Reiniciando en 3 segundos.")

		timer.delay(3, false, function()
			print("REINICIANDO...")
			msg.post("@system:", "reboot")
		end)
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
