-- -- game/player/player.script
-- local player_entity = require "core.entities.player"
local states = require  'core.constants.states'
local metrics = require "core.constants.metrics"
local speed = metrics.PLAYER_SPEED
local last_dir = "down"

function init(self)
	-- Add initialization code here
	-- Remove this function if not needed
	msg.post('.', 'acquire_input_focus')
	self.dir = vmath.vector3()
	self.current_anim = nil                                  -- [1]
	self.last_horizontal = "right"

end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

local function get_animation(self, is_moving)

	if is_moving then
		if self.dir.x > 0 then
			last_dir = "right"
			return hash("walk_right")
		elseif self.dir.x < 0 then
			last_dir = 'left'
			return hash('walk_left')
		elseif self.dir.y > 0 then
			last_dir = 'up'
			return hash('walk_up')
		elseif self.dir.y < 0 then
			last_dir = 'down'
			return hash('walk_down')
		end
	end

	local idle_anim = hash('idle_' .. last_dir)

	return idle_anim
end


function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed

	-- 1. Normalización: evita que corra más en diagonal
	if vmath.length_sqr(self.dir) > 1 then
		self.dir = vmath.normalize(self.dir)
	end

	-- 2. Movimiento
	local p = go.get_position()
	go.set_position(p + self.dir * speed * dt)

	local is_moving = vmath.length_sqr(self.dir) > 0
	local anim = get_animation(self, is_moving)

	-- 4. Reproducción
	if anim ~= self.current_anim then
		sprite.play_flipbook("#body", anim)
		self.current_anim = anim
	end

	self.dir = vmath.vector3()
	print(self.current_anim)
end

function fixed_update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
	if action_id == hash("move_down") then                        -- [1]
		self.dir.y = -1
	elseif action_id == hash("move_up") then
		self.dir.y = 1
	elseif action_id == hash("move_left") then                     -- [2]
		self.dir.x = -1
	elseif action_id == hash("move_right") then
		self.dir.x = 1
	end

end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end


