-- game/enemies/chaser.script
local constants = require "shared.constants"
local tracker = require "shared.tracker"

go.property("speed", 70)

-- Dentro de chaser.script, en la lógica de colisión con la bola:
local function die(self)
	-- Notificamos al Game Manager (usando la URL absoluta basada en tu imagen)
	msg.post("main:/game_manager#main", "enemy_defeated", { score = 10 })

	-- Efecto visual o sonido antes de desaparecer
	go.delete()
end

function update(self, dt)
	-- 1. ¿Hay un jugador registrado y está sano?
	if tracker.active_player_id then

		-- 2. Intentamos obtener la posición (con pcall por si el objeto fue borrado)
		local status, target_pos = pcall(go.get_position, tracker.active_player_id)

		if status then
			local my_pos = go.get_position()
			local dir = vmath.normalize(target_pos - my_pos)
			go.set_position(my_pos + dir * self.speed * dt)
		end
	else
		-- 3. Si el jugador está herido o no existe, la IA se detiene
		-- Aquí podrías poner una animación de "confusión"
		print("Herido")
		-- sprite.play_flipbook("#sprite", hash("idle"))
	end
end

function on_message(self, message_id, message, sender)
	-- Defold envía 'contact_point_response' cuando dos objetos con Collision Object chocan
	if message_id == hash("contact_point_response") then

		-- CASO 1: Colisión con el Jugador
		if message.other_group == hash("player") then
			-- Enviamos el mensaje de daño que definimos en el GDD
			msg.post(message.other_id, "take_damage")

			-- tracker.active_player_state = constants.PLAYER_WOUNDED
			print("LOG: Chaser atacó al hámster!") 

			-- CASO 2: Colisión con la Bola
		elseif message.other_group == hash("ball") then
			-- Por ahora, el enemigo se elimina al ser golpeado por la bola
			print("LOG: Chaser eliminado por la bola cargada!")
			die(self) 
		end
	end

	if message_id == hash("new_target") then
		-- Los enemigos cambian su objetivo inmediatamente al nuevo ID
		self.target_id = message.target_id
		print("IA: Cambiando objetivo al nuevo hámster.")
	end
end